use supermarket;

ALTER TABLE employees ADD FOREIGN KEY (dept_id) REFERENCES departments(d_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE managers ADD FOREIGN KEY (dept_id) REFERENCES departments(d_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE products ADD FOREIGN KEY (supplier_id) REFERENCES suppliers(s_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE customers MODIFY COLUMN phone VARCHAR(30) NOT NULL;
ALTER TABLE employees MODIFY COLUMN phone VARCHAR(30) NOT NULL;
ALTER TABLE managers MODIFY COLUMN phone VARCHAR(30) NOT NULL;
ALTER TABLE suppliers MODIFY COLUMN s_phone VARCHAR(30) NOT NULL;
ALTER TABLE promos DROP COLUMN consumptions;
ALTER TABLE purchases ADD COLUMN dept_id int;
ALTER TABLE purchases ADD FOREIGN KEY (dept_id) REFERENCES departments(d_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE purchases ADD COLUMN items VARCHAR(1000);
ALTER TABLE deliverys ADD FOREIGN KEY (purchase_id) REFERENCES purchases(p_id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE deliverys ADD FOREIGN KEY (license_id) REFERENCES licenses(l_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE licenses ADD FOREIGN KEY (delivery_id) REFERENCES deliverys(d_id) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE deliverys MODIFY COLUMN license_id INT UNIQUE;
ALTER TABLE managers ADD COLUMN branch_id INT UNIQUE;